#!/bin/sh

/usr/local/bin/python3 /data/InStock/instock/job/execute_daily_job.py

#清除缓存数据，只保留3天
MONTH=`date -d '' +%Y%m`
cd /data/InStock/instock/cache/hist && rm -rf !(${MONTH})
DATE=`date -d '' +%Y-%m-%d`
DATE_1=`date -d '-1 days' +%Y-%m-%d`
DATE_2=`date -d '-2 days' +%Y-%m-%d`
cd /data/InStock/instock/cache/hist/${MONTH} && rm -rf !(${DATE}|${DATE_1}|${DATE_2})