#!/bin/sh

#export PYTHONIOENCODING=utf-8
#export LANG=zh_CN.UTF-8
#export PYTHONPATH=/data/InStock
#export LC_CTYPE=zh_CN.UTF-8

/usr/local/bin/python3 /data/InStock/instock/job/basic_data_daily_job.py
